apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      #! - 192.168.65.111-192.168.65.120
      #!- 192.168.65.101-192.168.65.110
      - 172.18.1.1-172.18.1.100

