#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ def tap_pkgi():
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tap-install
#@ end

#@overlay/match by=overlay.subset(tap_pkgi())
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  annotations:
    kapp.k14s.io/change-rule.eso.1: "upsert after upserting eso/tap-sensitive-values"
