#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tanzu-sync-secrets
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/install"
    kapp.k14s.io/change-rule.1: "delete before deleting eso/install"
spec:
  provider:
    aws:
      service: SecretsManager
      region: #@ data.values.secrets.eso.aws.region
      auth:
        jwt:
          serviceAccountRef:
            name: tanzu-sync-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: #@ data.values.secrets.eso.aws.tanzu_sync_secrets.role_arn
  name: tanzu-sync-secrets
  namespace: tanzu-sync
